# Generated by Django 2.1.3 on 2018-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(height_field=300, null=True, upload_to='', width_field=300)),
                ('min_player_count', models.IntegerField(default=1)),
                ('max_player_count', models.IntegerField(default=99)),
                ('play_time', models.IntegerField(null=True)),
                ('publisher', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('initial', models.CharField(max_length=2, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('designs', models.ManyToManyField(to='boardgames.Boardgame')),
            ],
        ),
    ]
