# Generated by Django 2.1.3 on 2018-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designs',
            field=models.ManyToManyField(blank=True, null=True, to='boardgames.Boardgame'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='initial',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
