# Generated by Django 2.1.3 on 2018-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_auto_20181202_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designs',
            field=models.ManyToManyField(blank=True, to='boardgames.Boardgame'),
        ),
    ]
