# Generated by Django 2.1.3 on 2018-12-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_remove_designer_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(height_field='url_height', null=True, upload_to='', width_field='url_width'),
        ),
    ]
