# Generated by Django 2.1.3 on 2018-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_auto_20181202_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
